jobs: 
  circleci_test: 
    docker: # it uses the docker executor
      - image: markliou/python3-tensorflow-gpu:latest # specifically, a docker image with ruby 2.4.1
    steps:
      - checkout # this pulls code down from GitHub
      - run: python3 circleci_play.py
workflows:
  version: 2
  call_circleci_test: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - circleci_test